name: Deploy
run-name: TODO

on:
    push:
    workflow_dispatch:
        inputs:
            branch:
                default: main

permissions: {}

env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
    SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
    SSH_PORT: ${{ secrets.SSH_PORT}}

jobs:
    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: pwd
